import type {
  Action,
  ActionHistory,
  Actor,
  AgendaItem,
  BudgetMutation,
  BudgetRecord,
  Chapter,
  ChoiceList,
  Cluster,
  Config,
  Evidence,
  LogEntry,
  Meeting,
  MeetingParticipant,
  PlanningDependency,
  PlanningEntry,
  Project,
  ProjectClusterHistory,
  Report,
  ReportItem,
  Repositories,
  Topic,
  Update,
} from "../../domain"
import { InMemoryRepository } from "./in-memory-repository"

export function createInMemoryRepositories(): Repositories {
  return {
    chapters: new InMemoryRepository<Chapter>(),
    clusters: new InMemoryRepository<Cluster>(),
    projects: new InMemoryRepository<Project>(),
    projectClusterHistory: new InMemoryRepository<ProjectClusterHistory>(),
    actors: new InMemoryRepository<Actor>(),
    topics: new InMemoryRepository<Topic>(),
    updates: new InMemoryRepository<Update>(),
    actions: new InMemoryRepository<Action>(),
    actionHistory: new InMemoryRepository<ActionHistory>(),
    evidence: new InMemoryRepository<Evidence>(),
    planning: new InMemoryRepository<PlanningEntry>(),
    planningDependencies: new InMemoryRepository<PlanningDependency>(),
    budgets: new InMemoryRepository<BudgetRecord>(),
    budgetMutations: new InMemoryRepository<BudgetMutation>(),
    meetings: new InMemoryRepository<Meeting>(),
    meetingParticipants: new InMemoryRepository<MeetingParticipant>(),
    agendaItems: new InMemoryRepository<AgendaItem>(),
    reports: new InMemoryRepository<Report>(),
    reportItems: new InMemoryRepository<ReportItem>(),
    choiceLists: new InMemoryRepository<ChoiceList>(),
    config: new InMemoryRepository<Config>(),
    log: new InMemoryRepository<LogEntry>(),
  }
}
